const language = {
 msg2: "**🙄 - I can't add more than 5 channels**",
 msg3: "**🙄 - You can only upload files of this type ${formats}**",
 msg4: "**✅ - The line has been set for #${channel.name}**",
  msg5: "**🙄 - I can't find #${channel.name} in the auto-line channels**",
  msg6: "**✅ - #${channel.name} removed.**",
  msg7: "**🙄 - please provide some valid emojis.**",
  mag8: "**🙄 - i can't add more than 5 emojis.**",
   msg9: "**🙄 - I can't set more than 5 emojis per channel.",
 msg10: "**✅ - The emojis have been added for #${channel.name}.**",
  msg11: "**🙄 - I can't find #${channel.name} in the auto-reaction channels.**",
  msg12: "**✅ - #${channel.name} removed.**",
  msg13: "**the emojis in #${channel.name} are : ⤵️**",
  mag14: "**🙄 - I can't add more than 50 characters for the trigger or the response .**",
   msg15: "**🙄 - ${trigger} is already saved.**",
 msg16: "**✅ - ${trigger} has been saved.**",
  msg17: "**🙄 - I can't find index ${target} auto-reply**",
  msg18: "**✅ - ${obj.trigger} removed.**",
  msg19: "**🙄 - I can't find any reply in the server.**",
  mag20: "**🙄 - I can't save admins roles.**",
   msg21: "**I can't save this role**",
 msg22: "**🙄 - @${role.name} is already saved for ${type} roles.**",
  msg23: "**✅ - @${role.name} saved for ${type} roles.**",
  msg24: "**🙄 - I can't find @${role.name} in ${type} roles**",
  msg25: "🙄 - ** You can't ban @${target.user.username}. **",
  mag26: "🙄 - I couldn't ban that user. Please check my permissions and role position.",
   msg27: "",
 msg28: "Deleting messages..",
  msg29: "",
  msg30: "",
  msg31: "",
  mag32: "",
   msg33: "",
 msg34: "",
  msg35: "",
  msg36: "",
  msg37: "",
  mag38: "",
   msg39: "",
 msg40: "",
  msg41: "",
  msg42: "",
  msg43: "",
  mag44: "",
   msg45: "",
 msg46: "",
  msg47: "",
  msg48: "",
  msg49: "",
  mag50: "",
   msg51: "",
 msg52: "",
  msg53: "",
  msg54: "",
  msg55: "",
  mag56: "",
   msg57: "",
 msg58: "",
  msg59: "",
  msg60: "",
  msg61: "",
  mag62: "",
   msg63: "",
 msg64: "",
  msg65: "",
  msg66: "",
  msg67: "",
  mag20: "",
   msg21: "",
 msg22: "",
  msg23: "",
  msg24: "",
  msg25: "",
  mag26: "",
   msg3: "",
 msg4: "",
  msg5: "",
  msg6: "",
  msg7: "",
  mag8: "",
   msg9: "",
 msg10: "",
  msg11: "",
  msg12: "",
  msg13: "",
  mag14: "",
   msg15: "",
 msg16: "",
  msg17: "",
  msg18: "",
  msg19: "",
  mag20: "",
   msg21: "",
 msg22: "",
  msg23: "",
  msg24: "",
  msg25: "",
  mag26: "",
}
module.exports = language;
