const language = {
 msg2: "**🙄 - I can't add more than 5 channels**",
 msg3: "**🙄 - You can only upload files of this type ${formats}**",
 msg4: "**✅ - The line has been set for #${channel.name}**",
  msg5: "**🙄 - I can't find #${channel.name} in the auto-line channels**",
  msg6: "**✅ - #${channel.name} removed.**",
  msg7: "**🙄 - please provide some valid emojis.**",
  mag8: "**🙄 - i can't add more than 5 emojis.**",
   msg9: "**🙄 - I can't set more than 5 emojis per channel.",
 msg10: "**✅ - The emojis have been added for #${channel.name}.**",
  msg11: "**🙄 - I can't find #${channel.name} in the auto-reaction channels.**",
  msg12: "**✅ - #${channel.name} removed.**",
  msg13: "**the emojis in #${channel.name} are : ⤵️**",
  mag14: "**🙄 - I can't add more than 50 characters for the trigger or the response .**",
   msg15: "**🙄 - ${trigger} is already saved.**",
 msg16: "**✅ - ${trigger} has been saved.**",
  msg17: "**🙄 - I can't find index ${target} auto-reply**",
  msg18: "**✅ - ${obj.trigger} removed.**",
  msg19: "**🙄 - I can't find any reply in the server.**",
  mag20: "**🙄 - I can't save admins roles.**",
   msg21: "**I can't save this role**",
 msg22: "**🙄 - @${role.name} is already saved for ${type} roles.**",
  msg23: "**✅ - @${role.name} saved for ${type} roles.**",
  msg24: "**🙄 - I can't find @${role.name} in ${type} roles**",
  msg25: "🙄 - ** You can't ban @${target.user.username}. **",
  mag26: "🙄 - I couldn't ban that user. Please check my permissions and role position.",
   msg27: "✅ **${target.user.username} banned from the server! ✈️** ",
 msg28: "Deleting messages..",
  msg29: "**✅ - #${channel.name} has been choosed for greet channel.**",
  msg30: "**🙄 - You cannot choose a time greater than 60 seconds.**",
  msg31: "**✅ - Time selected successfully.**",
  mag32: "**✅ - greet announcements",
   msg33: "**🙄 - The message must be less than 250 characters.**",
 msg34: "**✅ - The changes have been saved.**",
  msg35: "**🔒 All channels have been hided",
  msg36: "**🔒 ${channel} has been hided",
  msg37: "🙄 - ** You can't kick @${target.user.username}. **",
  mag38: "🙄 - I couldn't kick that user. Please check my permissions and role position.",
   msg39: "✅ **@${target.user.username} kicked from the server! **",
 msg40: "**🔒 All channels have been locked",
  msg41: "**🔒 ${channel} has been locked",
  msg42: "**🙄 - Member is not in voice channel!**",
  msg43: "**✅  ${user.user.username} moved to ${channel.name}!**",
  mag44: "**🙄 - ${target.user.username} is already muted**",
   msg45: "🙄 - ** You can't mute @${target.user.username}. **",
 msg46: "🙄 - I couldn't change the roles for that user. Please check my permissions and role position.",
  msg47: "✅ **@${target.user.username} muted from the text! 🤐**",
  msg48: "🙄 - **${role}** is managed by integration and can't be given.",
  msg49: "🙄 - I couldn't change the roles for that user. Please check my permissions and role position.",
  mag50: "🙄 - **${role}**'s position higher than yours.",
   msg51: "✅ Changed roles for ${target.user.username}, **+${role.name}**",
 msg52: "🙄 - I can't find the role **${role}**.",
  msg53: "✅ Changed roles for ${target.user.username}, **-${role.name}**",
  msg54: "🙄 - I can't find the role **${role}**.",
  msg55: "**🙄 - You must have Administrator permission to do this command.**",
  mag56: "✅ Changing roles for ${members.size} members, +${role.name}",
   msg57: "✅ Changing roles for ${members.size} members, -${role.name}",
 msg58: "✅ Changing roles for ${members.size} members, +${role.name}",
  msg59: "✅ Changing roles for ${members.size} members, -${role.name}",
  msg60: "✅ Changing roles for ${members.size} members, +${role.name}",
  msg61: "✅ Changing roles for ${members.size} members, -${role.name}",
  mag62: "**🙄 -  You can't timeout @${target.user.username}. **",
   msg63: "**✅ ${target.user.username} has been timed out!**",
 msg64: "🙄 - I couldn't timeout that user. Please check my permissions and role position.",
  msg65: "",
  msg66: "",
  msg67: "",
  mag20: "",
   msg21: "",
 msg22: "",
  msg23: "",
  msg24: "",
  msg25: "",
  mag26: "",
   msg3: "",
 msg4: "",
  msg5: "",
  msg6: "",
  msg7: "",
  mag8: "",
   msg9: "",
 msg10: "",
  msg11: "",
  msg12: "",
  msg13: "",
  mag14: "",
   msg15: "",
 msg16: "",
  msg17: "",
  msg18: "",
  msg19: "",
  mag20: "",
   msg21: "",
 msg22: "",
  msg23: "",
  msg24: "",
  msg25: "",
  mag26: "",
}
module.exports = language;
